import shoe1 from "../assets/images/shoe1.jpeg";
import shoe2 from "../assets/images/shoe2.jpeg";
import shoe3 from "../assets/images/shoe3.jpeg";
import shoe4 from "../assets/images/shoe4.jpeg";
import shoe5 from "../assets/images/shoe5.jpeg";
import shoe6 from "../assets/images/big-shoe1.png";
import shoe7 from "../assets/images/big-shoe2.png";
import shoe8 from "../assets/images/big-shoe3.png";
import shoe9 from "../assets/images/big-shoe4.jpeg";
import shoe10 from "../assets/images/Home-shoe.png";

const productsData = [
    {
        id: 1,
        name: "Casual Sneakers",
        price: 999,
        originalPrice: 1299,
        discount: 30,
        size: 8,
        brand: "Nike",
        gender: "Unisex",
        occasion: "Casual",
        colors: ["White", "Black"],
        image: shoe1,
        offer: "Buy 2, Save Extra 10%"
    },
    {
        id: 2,
        name: "Adidas Ultraboost",
        price: 150,
        originalPrice: 180,
        discount: 17,
        size: 9,
        brand: "Adidas",
        gender: "Women",
        occasion: "Running",
        colors: ["Blue", "Pink"],
        image: shoe2,
        offer: "Free Shipping"
    },
    {
        id: 3,
        name: "Puma Running Shoes",
        price: 1200,
        originalPrice: 1500,
        discount: 20,
        size: 7,
        brand: "Puma",
        gender: "Men",
        occasion: "Running",
        colors: ["Black", "Red"],
        image: shoe3,
        offer: "Buy 1, Get 10% Off"
    },
    {
        id: 4,
        name: "Reebok Classic",
        price: 800,
        originalPrice: 1100,
        discount: 27,
        size: 10,
        brand: "Reebok",
        gender: "Unisex",
        occasion: "Casual",
        colors: ["White", "Green"],
        image: shoe4,
        offer: "Limited Stock"
    },
    {
        id: 5,
        name: "Nike Air Max",
        price: 1400,
        originalPrice: 2000,
        discount: 30,
        size: 8,
        brand: "Nike",
        gender: "Men",
        occasion: "Sports",
        colors: ["Black", "Yellow"],
        image: shoe5,
        offer: "Free Shipping"
    },
    {
        id: 6,
        name: "Adidas Stan Smith",
        price: 900,
        originalPrice: 1200,
        discount: 25,
        size: 9,
        brand: "Adidas",
        gender: "Women",
        occasion: "Casual",
        colors: ["White", "Blue"],
        image: shoe6,
        offer: "Buy 2, Save Extra 15%"
    },
    {
        id: 7,
        name: "Puma Suede Classic",
        price: 1100,
        originalPrice: 1400,
        discount: 21,
        size: 7,
        brand: "Puma",
        gender: "Unisex",
        occasion: "Casual",
        colors: ["Black", "White"],
        image: shoe7,
        offer: "Limited Offer"
    },
    {
        id: 8,
        name: "Reebok Zig Kinetica",
        price: 1300,
        originalPrice: 1600,
        discount: 19,
        size: 10,
        brand: "Reebok",
        gender: "Men",
        occasion: "Running",
        colors: ["Grey", "Orange"],
        image: shoe8,
        offer: "Free Shipping"
    },
    {
        id: 9,
        name: "Nike React Infinity",
        price: 1600,
        originalPrice: 2200,
        discount: 27,
        size: 8,
        brand: "Nike",
        gender: "Women",
        occasion: "Running",
        colors: ["Pink", "White"],
        image: shoe9,
        offer: "Buy 1, Get 20% Off"
    },
    {
        id: 10,
        name: "Adidas NMD",
        price: 1000,
        originalPrice: 1300,
        discount: 23,
        size: 9,
        brand: "Adidas",
        gender: "Unisex",
        occasion: "Casual",
        colors: ["Black", "Green"],
        image: shoe10,
        offer: "Limited Stock"
    },
    {
        id: 11,
        name: "Puma RS-X",
        price: 950,
        originalPrice: 1200,
        discount: 21,
        size: 7,
        brand: "Puma",
        gender: "Men",
        occasion: "Sports",
        colors: ["Blue", "White"],
        image: shoe1,
        offer: "Free Shipping"
    },
    {
        id: 12,
        name: "Reebok Nano X",
        price: 1400,
        originalPrice: 1800,
        discount: 22,
        size: 10,
        brand: "Reebok",
        gender: "Women",
        occasion: "Training",
        colors: ["Black", "Red"],
        image: shoe2,
        offer: "Buy 2, Save Extra 10%"
    },
    {
        id: 13,
        name: "Nike Free RN",
        price: 1100,
        originalPrice: 1500,
        discount: 27,
        size: 8,
        brand: "Nike",
        gender: "Unisex",
        occasion: "Running",
        colors: ["White", "Yellow"],
        image: shoe3,
        offer: "Limited Offer"
    },
    {
        id: 14,
        name: "Adidas Superstar",
        price: 850,
        originalPrice: 1100,
        discount: 23,
        size: 9,
        brand: "Adidas",
        gender: "Men",
        occasion: "Casual",
        colors: ["White", "Black"],
        image: shoe4,
        offer: "Free Shipping"
    },
    {
        id: 15,
        name: "Puma Future Rider",
        price: 1200,
        originalPrice: 1600,
        discount: 25,
        size: 7,
        brand: "Puma",
        gender: "Women",
        occasion: "Casual",
        colors: ["Pink", "Blue"],
        image: shoe5,
        offer: "Buy 1, Get 15% Off"
    },
    {
        id: 16,
        name: "Reebok Club C",
        price: 900,
        originalPrice: 1200,
        discount: 25,
        size: 10,
        brand: "Reebok",
        gender: "Unisex",
        occasion: "Casual",
        colors: ["White", "Green"],
        image: shoe6,
        offer: "Limited Stock"
    },
    {
        id: 17,
        name: "Nike Zoom Pegasus",
        price: 1500,
        originalPrice: 2000,
        discount: 25,
        size: 8,
        brand: "Nike",
        gender: "Men",
        occasion: "Running",
        colors: ["Black", "White"],
        image: shoe7,
        offer: "Free Shipping"
    },
    {
        id: 18,
        name: "Adidas Gazelle",
        price: 950,
        originalPrice: 1300,
        discount: 27,
        size: 9,
        brand: "Adidas",
        gender: "Women",
        occasion: "Casual",
        colors: ["Red", "White"],
        image: shoe8,
        offer: "Buy 2, Save Extra 10%"
    },
    {
        id: 19,
        name: "Puma Cali Sport",
        price: 1100,
        originalPrice: 1400,
        discount: 21,
        size: 7,
        brand: "Puma",
        gender: "Unisex",
        occasion: "Casual",
        colors: ["White", "Black"],
        image: shoe9,
        offer: "Limited Offer"
    },
    {
        id: 20,
        name: "Reebok Freestyle",
        price: 1300,
        originalPrice: 1700,
        discount: 24,
        size: 10,
        brand: "Reebok",
        gender: "Women",
        occasion: "Training",
        colors: ["Pink", "Grey"],
        image: shoe10,
        offer: "Free Shipping"
    },
    {
        id: 21,
        name: "Nike Air Force 1",
        price: 1200,
        originalPrice: 1600,
        discount: 25,
        size: 8,
        brand: "Nike",
        gender: "Men",
        occasion: "Casual",
        colors: ["White", "Blue"],
        image: shoe1,
        offer: "Buy 1, Get 10% Off"
    },
    {
        id: 22,
        name: "Adidas Yeezy Boost",
        price: 1800,
        originalPrice: 2400,
        discount: 25,
        size: 9,
        brand: "Adidas",
        gender: "Unisex",
        occasion: "Casual",
        colors: ["Black", "Yellow"],
        image: shoe2,
        offer: "Limited Stock"
    },
    {
        id: 23,
        name: "Puma Ignite Flash",
        price: 1000,
        originalPrice: 1300,
        discount: 23,
        size: 7,
        brand: "Puma",
        gender: "Men",
        occasion: "Running",
        colors: ["Blue", "White"],
        image: shoe3,
        offer: "Free Shipping"
    },
    {
        id: 24,
        name: "Reebok Pump",
        price: 1400,
        originalPrice: 1800,
        discount: 22,
        size: 10,
        brand: "Reebok",
        gender: "Women",
        occasion: "Sports",
        colors: ["Black", "Red"],
        image: shoe4,
        offer: "Buy 2, Save Extra 15%"
    },
    {
        id: 25,
        name: "Nike Epic React",
        price: 1600,
        originalPrice: 2200,
        discount: 27,
        size: 8,
        brand: "Nike",
        gender: "Unisex",
        occasion: "Running",
        colors: ["White", "Green"],
        image: shoe5,
        offer: "Limited Offer"
    },
    {
        id: 26,
        name: "Adidas Terrex",
        price: 1100,
        originalPrice: 1500,
        discount: 27,
        size: 9,
        brand: "Adidas",
        gender: "Men",
        occasion: "Hiking",
        colors: ["Grey", "Black"],
        image: shoe6,
        offer: "Free Shipping"
    },
    {
        id: 27,
        name: "Puma LQD Cell",
        price: 1200,
        originalPrice: 1600,
        discount: 25,
        size: 7,
        brand: "Puma",
        gender: "Women",
        occasion: "Training",
        colors: ["Pink", "White"],
        image: shoe7,
        offer: "Buy 1, Get 20% Off"
    },
    {
        id: 28,
        name: "Reebok CrossFit",
        price: 1500,
        originalPrice: 2000,
        discount: 25,
        size: 10,
        brand: "Reebok",
        gender: "Unisex",
        occasion: "Training",
        colors: ["Black", "Yellow"],
        image: shoe8,
        offer: "Limited Stock"
    },
    {
        id: 29,
        name: "Nike Joyride",
        price: 1400,
        originalPrice: 1900,
        discount: 26,
        size: 8,
        brand: "Nike",
        gender: "Men",
        occasion: "Running",
        colors: ["Blue", "White"],
        image: shoe9,
        offer: "Free Shipping"
    },
    {
        id: 30,
        name: "Adidas Samba",
        price: 900,
        originalPrice: 1200,
        discount: 25,
        size: 9,
        brand: "Adidas",
        gender: "Women",
        occasion: "Casual",
        colors: ["White", "Red"],
        image: shoe10,
        offer: "Buy 2, Save Extra 10%"
    }
];

export default productsData;